{
 "title": "DESL Wasserkraftwerk",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Input Power",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Datum AS \"time\",\n  Power_Active\nFROM sdm230\nORDER BY Datum"
    }
   ]
  },
  {
   "title": "Flow Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Datum AS \"time\",\n  flowRate\nFROM esp32\nORDER BY Datum"
    }
   ]
  },
  {
   "title": "Drehzahl",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Datum AS \"time\",\n  drehzahl\nFROM esp32\nORDER BY Datum"
    }
   ]
  },
  {
   "title": "Output Power",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Datum AS \"time\",\n  Power_L1 + Power_L2 + Power_L3\nFROM sdm630\nORDER BY Datum"
    }
   ]
  },
  {
   "title": "Sensors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flow Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "flowlpm" } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  flowRate\nFROM esp32\nORDER BY Datum"
      }
     ]
    },
    {
     "title": "Drehzahl",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  drehzahl\nFROM esp32\nORDER BY Datum"
      }
     ]
    },
    {
     "title": "Total Flow since start",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "Liter" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  total\nFROM esp32\nORDER BY Datum"
      }
     ]
    },
    {
     "title": "Rotation Frequency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  drehzahl / 60 AS \"Rotation Frequency\"\nFROM esp32\nORDER BY Datum"
      }
     ]
    }
   ]
  },
  {
   "title": "Generator ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Voltage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Voltage_L1N,\n  Voltage_L2N,\n  Voltage_L3N\nFROM sdm630\nORDER BY Datum"
      }
     ]
    },
    {
     "title": "Frequency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Frequency\nFROM sdm630\nORDER BY Datum"
      }
     ]
    },
    {
     "title": "Current",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Current_L1,\n  Current_L2,\n  Current_L3\nFROM sdm630\nORDER BY Datum"
      }
     ]
    },
    {
     "title": "Active Power",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Power_L1,\n  Power_L2,\n  Power_L3\nFROM sdm630\nORDER BY Datum"
      }
     ]
    },
    {
     "title": "Power Factor",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "PF" } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Power_factor_L1,\n  Power_factor_L2,\n  Power_factor_L3\nFROM sdm630\nORDER BY Datum"
      }
     ]
    },
    {
     "title": "Reactive Power",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "voltampreact" } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Power_L1 * (1 - Power_factor_L1) AS \"Reactive Power L1\",\n  Power_L2 * (1 - Power_factor_L2) AS \"Reactive Power L2\",\n  Power_L3 * (1 - Power_factor_L3) AS \"Reactive Power L3\"\nFROM sdm630\nORDER BY Datum"
      }
     ]
    }
   ]
  },
  {
   "title": "Water Pump",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Voltage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Voltage\nFROM sdm230\nORDER BY Datum"
      }
     ]
    },
    {
     "title": "Frequency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Frequency\nFROM sdm230\nORDER BY Datum"
      }
     ]
    },
    {
     "title": "Current",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Current\nFROM sdm230\nORDER BY Datum"
      }
     ]
    },
    {
     "title": "Active / Reactive Power",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Power_Active,\n  Power_Reactive\nFROM sdm230\nORDER BY Datum"
      }
     ]
    }
   ]
  }
 ]
}