{
 "title": "Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Imported & Exported Power",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Maximum Demand Active Power",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Maximum_Import_Demand_Power_Active\nFROM sdm230\nORDER BY Datum"
      }
     ]
    },
    {
     "title": "Maximum Exported Active Power",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Maximum_Export_Demand_Power_Active\nFROM sdm230\nORDER BY Datum"
      }
     ]
    },
    {
     "title": "Demand Active Power",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Import_Demand_Power_Active\nFROM sdm230\nORDER BY Datum"
      }
     ]
    },
    {
     "title": "Exported Active Power",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Export_Demand_Power_Active\nFROM sdm230\nORDER BY Datum"
      }
     ]
    },
    {
     "title": "Demand Active Energy",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Imported_Energy_Active\nFROM sdm230\nORDER BY Datum"
      }
     ]
    },
    {
     "title": "Exported Active Energy",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Exported_Energy_Active\nFROM sdm230\nORDER BY Datum"
      }
     ]
    },
    {
     "title": "Demand Reactive Energy",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "varh" } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Imported_Energy_Reactive\nFROM sdm230\nORDER BY Datum"
      }
     ]
    },
    {
     "title": "Exported Reactive Energy",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "varh" } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Exported_Energy_Reactive\nFROM sdm230\nORDER BY Datum"
      }
     ]
    }
   ]
  },
  {
   "title": "Gauge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Current\nFROM sdm230\nORDER BY Datum"
      }
     ]
    },
    {
     "title": "Voltage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Voltage\nFROM sdm230\nORDER BY Datum"
      }
     ]
    },
    {
     "title": "Active Power",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Power_Active\nFROM sdm230\nORDER BY Datum"
      }
     ]
    },
    {
     "title": "Total Active Energy",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Total_Energy_Active\nFROM sdm230\nORDER BY Datum"
      }
     ]
    },
    {
     "title": "Anzahl Datenpunkte",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  ID\nFROM sdm230\nORDER BY Datum"
      }
     ]
    }
   ]
  },
  {
   "title": "Voltage & Current",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Voltage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Voltage\nFROM sdm230\nORDER BY Datum"
      }
     ]
    },
    {
     "title": "Current",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Current\nFROM sdm230\nORDER BY Datum"
      }
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Power",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Power_Active\nFROM sdm230\nORDER BY Datum"
      }
     ]
    },
    {
     "title": "Reactive Power",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "voltampreact" } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Power_Reactive\nFROM sdm230\nORDER BY Datum"
      }
     ]
    },
    {
     "title": "Apparent Power",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "voltamp" } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Power_Apparent\nFROM sdm230\nORDER BY Datum"
      }
     ]
    },
    {
     "title": "Power Factor",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "PF" } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Power_Factor\nFROM sdm230\nORDER BY Datum"
      }
     ]
    }
   ]
  },
  {
   "title": "Frequency & Phase Angle",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Frequency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Frequency\nFROM sdm230\nORDER BY Datum"
      }
     ]
    },
    {
     "title": "Phase Angle",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "degree" } },
     "targets": [
      {
       "rawSql": "SELECT\n  Datum AS \"time\",\n  Phase_Angle\nFROM sdm230\nORDER BY Datum"
      }
     ]
    }
   ]
  }
 ]
}