{
 "title": "SDM630 Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Voltage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Voltage L1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  Datum AS \"time\",\n  Voltage_L1N\nFROM sdm630\nORDER BY Datum"
    }
   ]
  },
  {
   "title": "Voltage L2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  Datum AS \"time\",\n  Voltage_L2N\nFROM sdm630\nORDER BY Datum"
    }
   ]
  },
  {
   "title": "Voltage L3",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  Datum AS \"time\",\n  Voltage_L3N\nFROM sdm630\nORDER BY Datum"
    }
   ]
  }
 ]
}